name: Log Commits to Notion

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  log-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Log commit to Notion
        uses: d-stelmach/notion-commit-log@v1
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-database-id: ${{ secrets.NOTION_DATABASE_ID }}
